# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Pull Request - Artifact Upload

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
    paths-ignore:
      - '**.md'

jobs:
  build:
    runs-on: windows-2019

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: setup-msbuild
      uses: microsoft/setup-msbuild@v2

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v2

    - name: Restore Packages
      run: nuget restore ComicRack.sln

    - name: Build solution
      run: msbuild ComicRack\ComicRack.csproj -t:rebuild -property:Configuration=Release

    - name: Package Files
      run: powershell Compress-Archive -Path 'ComicRack\bin\Release\*' -DestinationPath 'ComicRackCE_PR.zip' -Force

    - name: Get short sha
      id: vars
      run: echo "sha_short=$(git rev-parse --short HEAD)" >> $env:GITHUB_OUTPUT

    - name: Compile installer
      uses: Minionguyjpro/Inno-Setup-Action@v1.2.3
      with:
        path: Installer.iss
        options: /DMyAppVersion=nightly-${{ steps.vars.outputs.sha_short }} /DMyAppSetupFile=ComicRackCESetup_PR

    - name: Upload artifacts
      id: upload
      uses: actions/upload-artifact@v4
      with:
        name: "ComicRackCESetup_PR.exe"
        path: "ComicRackCESetup_PR.exe"
        if-no-files-found: error